stages:
  - build_and_push

variables:
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA
  APP_NAME: "netology-diploma-app"

build_and_push:
  stage: build_and_push
  image: docker:24.0.5
  
  before_script:
    - apk add --no-cache curl bash
    - curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
    - export PATH="$PATH:$HOME/yandex-cloud/bin"
    - echo "$YC_SA_KEY" > /tmp/sa_key.json
    - yc config profile create ci-profile || true
    - yc config set service-account-key /tmp/sa_key.json
    - YC_TOKEN=$(yc iam create-token)
    - echo "$YC_TOKEN" | docker login --username iam --password-stdin cr.yandex

  script:
    - |
      echo "Building Docker image: $APP_NAME:$IMAGE_TAG"
      docker build -t $APP_NAME:$IMAGE_TAG .
      docker tag $APP_NAME:$IMAGE_TAG $APP_NAME:latest
      
      echo "Tagging for Yandex Container Registry..."
      docker tag $APP_NAME:$IMAGE_TAG cr.yandex/$YCR_REGISTRY_ID/$APP_NAME:$IMAGE_TAG
      docker tag $APP_NAME:latest cr.yandex/$YCR_REGISTRY_ID/$APP_NAME:latest
      
      echo "Pushing images to Yandex Container Registry..."
      docker push cr.yandex/$YCR_REGISTRY_ID/$APP_NAME:$IMAGE_TAG
      docker push cr.yandex/$YCR_REGISTRY_ID/$APP_NAME:latest
      
      echo "Cleanup: removing local key"
      rm -f /tmp/sa_key.json

  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_TAG'